services:
  n8n:
    image: n8nio/n8n:latest
    container_name: tpm-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Bangkok
      - TZ=Asia/Bangkok
      - N8N_SECURE_COOKIE=false
      - N8N_RUNNERS_ENABLED=true
      - DB_TYPE=sqlite
      - N8N_USER_FOLDER=/home/node/.n8n
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/home/node/.n8n/workflows
    networks:
      - tpm-net

volumes:
  n8n_data:

networks:
  tpm-net:
    external: false
