"""
tpm_progress.slides - render WeekData into a 6-slide .pptx
ref: MASTER_PLAN_v5.md § 16.4

6 slides:
    1. Title cover (date range, intern name, week number)
    2. This week at a glance (counts + headline metrics)
    3. Top tasks completed (top-3 by duration, with subject + outcome)
    4. Quality + reliability (success rate, latency p90, egress, failures)
    5. Tools / artifacts produced (files + commits + libs)
    6. Lessons learned + next week (auditor findings + plan)
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from tpm_progress.data import WeekData

log = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT_DIR = REPO_ROOT / "output" / "progress_reports"

# Color palette - dark slate + accent (matches Chainlit dark theme)
COLOR_BG = (28, 30, 38)         # near black
COLOR_PRIMARY = (113, 152, 218)  # cool blue accent
COLOR_TEXT = (235, 237, 242)    # off-white
COLOR_DIM = (155, 162, 178)     # secondary text
COLOR_OK = (107, 191, 105)      # green
COLOR_WARN = (231, 165, 80)     # amber
COLOR_BAD = (218, 110, 100)     # soft red


# ============================================================
# Helpers
# ============================================================
def _add_text(slide, left, top, width, height, text: str, *,
              font_size=18, bold=False, color=COLOR_TEXT, align=None):
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    box = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
    tf = box.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    if align is not None:
        p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size = Pt(font_size)
    run.font.bold = bold
    run.font.color.rgb = RGBColor(*color)
    return box


def _add_bullet(slide, left, top, width, height, lines: list[str], *,
                font_size=14, color=COLOR_TEXT, bullet_color=COLOR_PRIMARY):
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    box = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
    tf = box.text_frame
    tf.word_wrap = True
    for i, line in enumerate(lines):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        bullet_run = p.add_run()
        bullet_run.text = "• "
        bullet_run.font.size = Pt(font_size + 2)
        bullet_run.font.color.rgb = RGBColor(*bullet_color)
        text_run = p.add_run()
        text_run.text = line
        text_run.font.size = Pt(font_size)
        text_run.font.color.rgb = RGBColor(*color)
    return box


def _set_slide_bg(slide, color):
    from pptx.dml.color import RGBColor
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(*color)


def _fmt_int(n: int) -> str:
    return f"{n:,}"


def _fmt_seconds(ms: int) -> str:
    if ms <= 0:
        return "n/a"
    if ms < 1000:
        return f"{ms} ms"
    return f"{ms/1000:.1f} s"


# ============================================================
# Slide builders
# ============================================================
def _slide_title(prs, week: WeekData):
    blank_layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank_layout)
    _set_slide_bg(slide, COLOR_BG)

    _add_text(slide, 0.6, 1.4, 12, 1.2, "TPM AI — Weekly Progress",
              font_size=44, bold=True, color=COLOR_PRIMARY)
    _add_text(slide, 0.6, 2.6, 12, 0.6,
              f"{week.week_start}  →  {week.week_end}",
              font_size=24, color=COLOR_TEXT)
    _add_text(slide, 0.6, 3.4, 12, 0.5,
              f"Sessions: {week.n_sessions}   "
              f"·  Active days: {week.n_days_with_activity}   "
              f"·  Artifacts: {len(week.artifacts)}",
              font_size=18, color=COLOR_DIM)

    _add_text(slide, 0.6, 6.5, 12, 0.4,
              "Generated by TPM AI Night Cycle  ·  local LLM (Qwen3-8B)  ·  open-source first",
              font_size=11, color=COLOR_DIM)


def _slide_at_a_glance(prs, week: WeekData):
    blank_layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank_layout)
    _set_slide_bg(slide, COLOR_BG)

    _add_text(slide, 0.6, 0.4, 12, 0.7, "📊 At a glance",
              font_size=32, bold=True, color=COLOR_PRIMARY)

    success_rate = (
        round(week.n_done / week.n_sessions * 100, 1) if week.n_sessions else 0
    )

    # 4 KPI cards across the slide
    kpis = [
        ("Sessions", _fmt_int(week.n_sessions), COLOR_PRIMARY),
        ("Success rate", f"{success_rate}%",
         COLOR_OK if success_rate >= 80 else COLOR_WARN),
        ("Latency p90", _fmt_seconds(week.p90_duration_ms), COLOR_TEXT),
        ("Egress blocks", _fmt_int(week.n_egress_blocks), COLOR_OK),
    ]
    card_w = 2.9
    for i, (label, value, color) in enumerate(kpis):
        left = 0.6 + i * (card_w + 0.15)
        _add_text(slide, left, 1.5, card_w, 0.5, label,
                  font_size=14, color=COLOR_DIM)
        _add_text(slide, left, 2.0, card_w, 1.2, value,
                  font_size=42, bold=True, color=color)

    # Breakdown by action and provider
    if week.by_action:
        lines = [f"{action}: {n}" for action, n in
                 sorted(week.by_action.items(), key=lambda x: -x[1])[:5]]
        _add_text(slide, 0.6, 4.3, 6, 0.4, "Top intent actions",
                  font_size=16, bold=True, color=COLOR_PRIMARY)
        _add_bullet(slide, 0.6, 4.7, 6, 2.5, lines, font_size=13)

    if week.by_provider or week.by_worker:
        rhs = []
        for k, v in sorted(week.by_provider.items(), key=lambda x: -x[1])[:3]:
            rhs.append(f"search → {k}: {v}")
        for k, v in sorted(week.by_worker.items(), key=lambda x: -x[1])[:3]:
            rhs.append(f"worker → {k}: {v}")
        _add_text(slide, 6.8, 4.3, 6, 0.4, "Routing breakdown",
                  font_size=16, bold=True, color=COLOR_PRIMARY)
        _add_bullet(slide, 6.8, 4.7, 6, 2.5, rhs or ["(no routing data)"],
                    font_size=13)


def _slide_top_tasks(prs, week: WeekData):
    blank_layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank_layout)
    _set_slide_bg(slide, COLOR_BG)

    _add_text(slide, 0.6, 0.4, 12, 0.7, "🎯 Top tasks this week",
              font_size=32, bold=True, color=COLOR_PRIMARY)

    if not week.top_tasks:
        _add_text(slide, 0.6, 3, 12, 1, "(no completed sessions to highlight)",
                  font_size=18, color=COLOR_DIM)
        return

    for i, t in enumerate(week.top_tasks[:3]):
        top = 1.4 + i * 1.7
        phase_color = COLOR_OK if t.get("phase") == "done" else COLOR_BAD
        _add_text(slide, 0.6, top, 0.7, 0.5, f"#{i+1}",
                  font_size=24, bold=True, color=COLOR_PRIMARY)
        _add_text(slide, 1.4, top, 9, 0.5,
                  t.get("user_request", "?"),
                  font_size=18, bold=True, color=COLOR_TEXT)
        _add_text(slide, 1.4, top + 0.55, 9, 0.5,
                  f"action: {t.get('action','?')}   "
                  f"·  subject: {t.get('subject','-') or '-'}   "
                  f"·  duration: {t.get('duration_s')}s",
                  font_size=13, color=COLOR_DIM)
        _add_text(slide, 11, top, 2, 0.5,
                  t.get("phase", "?").upper(),
                  font_size=16, bold=True, color=phase_color)


def _slide_activity(prs, week: WeekData):
    """Time-breakdown slide: in-AI vs out-of-AI minutes + categories."""
    blank_layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank_layout)
    _set_slide_bg(slide, COLOR_BG)

    _add_text(slide, 0.6, 0.4, 12, 0.7, "⏱️ Time breakdown (manual log)",
              font_size=32, bold=True, color=COLOR_PRIMARY)

    a = week.activity
    total_h = a.total_min / 60.0
    in_ai_h = a.total_with_ai_min / 60.0
    out_ai_h = a.total_without_ai_min / 60.0
    ratio_pct = round(in_ai_h / total_h * 100, 1) if total_h > 0 else 0

    if a.n_entries == 0:
        _add_text(slide, 0.6, 3, 12, 1.5,
                  "(no manual activity entries this week)\n"
                  "Use:  python scripts/log_activity.py --interactive",
                  font_size=18, color=COLOR_DIM)
        return

    # 4 KPI cards
    kpis = [
        ("Entries", _fmt_int(a.n_entries), COLOR_PRIMARY),
        ("Total hours", f"{total_h:.1f}", COLOR_TEXT),
        ("With AI", f"{in_ai_h:.1f}h ({ratio_pct}%)", COLOR_OK),
        ("Without AI", f"{out_ai_h:.1f}h", COLOR_TEXT),
    ]
    card_w = 2.9
    for i, (label, value, color) in enumerate(kpis):
        left = 0.6 + i * (card_w + 0.15)
        _add_text(slide, left, 1.5, card_w, 0.5, label,
                  font_size=14, color=COLOR_DIM)
        _add_text(slide, left, 2.0, card_w, 1.2, value,
                  font_size=36, bold=True, color=color)

    # Breakdown by category - left half
    if a.by_category_min:
        sorted_cats = sorted(a.by_category_min.items(), key=lambda kv: -kv[1])[:8]
        lines = [f"{cat}: {mins/60:.1f}h ({mins:.0f} min)" for cat, mins in sorted_cats]
        _add_text(slide, 0.6, 4.3, 6, 0.4, "Top categories",
                  font_size=16, bold=True, color=COLOR_PRIMARY)
        _add_bullet(slide, 0.6, 4.7, 6, 2.5, lines, font_size=13)

    # Right half: AI usage context
    rhs = [
        f"AI sessions this week: {week.n_sessions}",
        f"Active days w/ entries: {a.n_days_with_entries}/7",
        f"AI session avg: {_fmt_seconds(week.avg_duration_ms)}",
    ]
    if total_h > 0 and in_ai_h > 0:
        rhs.append("")
        rhs.append(f"AI assist saves time on {ratio_pct}% of logged work")
    _add_text(slide, 6.8, 4.3, 6, 0.4, "AI utilization",
              font_size=16, bold=True, color=COLOR_PRIMARY)
    _add_bullet(slide, 6.8, 4.7, 6, 2.5, rhs, font_size=13)


def _slide_quality(prs, week: WeekData):
    blank_layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank_layout)
    _set_slide_bg(slide, COLOR_BG)

    _add_text(slide, 0.6, 0.4, 12, 0.7, "📈 Quality & reliability",
              font_size=32, bold=True, color=COLOR_PRIMARY)

    metrics = [
        f"Total sessions: {week.n_sessions}",
        f"Completed: {week.n_done}   ·   Failed: {week.n_failed}",
        f"Avg duration: {_fmt_seconds(week.avg_duration_ms)}   "
        f"·   p90: {_fmt_seconds(week.p90_duration_ms)}",
        f"Egress blocks (security): {week.n_egress_blocks}",
        f"Auditor findings logged: {len(week.auditor_findings)}",
    ]
    _add_bullet(slide, 0.6, 1.4, 6, 3.5, metrics, font_size=15)

    if week.repeated_failures:
        _add_text(slide, 0.6, 4.8, 12, 0.5, "⚠️ Repeated failures",
                  font_size=18, bold=True, color=COLOR_WARN)
        _add_bullet(slide, 0.6, 5.3, 12, 1.8, week.repeated_failures,
                    font_size=13, bullet_color=COLOR_WARN)

    if week.night_briefs:
        _add_text(slide, 6.8, 1.4, 6, 0.5, "🌙 Night briefs run",
                  font_size=18, bold=True, color=COLOR_PRIMARY)
        _add_bullet(slide, 6.8, 1.9, 6, 3.5, week.night_briefs[-7:],
                    font_size=13)


def _slide_artifacts(prs, week: WeekData):
    blank_layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank_layout)
    _set_slide_bg(slide, COLOR_BG)

    _add_text(slide, 0.6, 0.4, 12, 0.7, "🔧 Tools & artifacts",
              font_size=32, bold=True, color=COLOR_PRIMARY)

    # Artifacts produced
    if week.artifacts:
        _add_text(slide, 0.6, 1.3, 6, 0.5,
                  f"Files produced ({len(week.artifacts)})",
                  font_size=16, bold=True, color=COLOR_PRIMARY)
        lines = [
            f"{a['name']}  ({a['kind']}, {a['size_kb']} KB, {a['mtime']})"
            for a in week.artifacts[:8]
        ]
        if len(week.artifacts) > 8:
            lines.append(f"... +{len(week.artifacts) - 8} more")
        _add_bullet(slide, 0.6, 1.8, 6.2, 5.0, lines, font_size=11)
    else:
        _add_text(slide, 0.6, 1.8, 6, 0.5, "(no artifacts produced)",
                  font_size=14, color=COLOR_DIM)

    # Git commits
    if week.git_commits:
        _add_text(slide, 7.0, 1.3, 6, 0.5,
                  f"Code commits ({len(week.git_commits)})",
                  font_size=16, bold=True, color=COLOR_PRIMARY)
        lines = [c[:80] for c in week.git_commits[:8]]
        if len(week.git_commits) > 8:
            lines.append(f"... +{len(week.git_commits) - 8} more")
        _add_bullet(slide, 7.0, 1.8, 6, 5.0, lines, font_size=10)

    # Tools added (banner at the bottom)
    if week.tools_added:
        names = ", ".join(t.get("name", "?") for t in week.tools_added[:6])
        _add_text(slide, 0.6, 6.7, 12, 0.5,
                  f"📦 New OSS deps: {names}",
                  font_size=12, color=COLOR_DIM)


def _slide_lessons(prs, week: WeekData):
    blank_layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank_layout)
    _set_slide_bg(slide, COLOR_BG)

    _add_text(slide, 0.6, 0.4, 12, 0.7, "💡 Lessons & next week",
              font_size=32, bold=True, color=COLOR_PRIMARY)

    # Lessons (auditor findings, repeated failures)
    lessons: list[str] = []
    if week.auditor_findings:
        for f in week.auditor_findings[:3]:
            lessons.append(f"Auditor: {f[:90]}")
    if week.repeated_failures:
        for f in week.repeated_failures[:3]:
            lessons.append(f"Repeated fail: {f}")
    if not lessons:
        lessons.append("No anti-patterns detected this week ✅")

    _add_text(slide, 0.6, 1.3, 6, 0.5, "Lessons learned",
              font_size=18, bold=True, color=COLOR_PRIMARY)
    _add_bullet(slide, 0.6, 1.8, 6.2, 4.0, lessons, font_size=13)

    # Next week plan (template)
    plan = [
        "Continue Phase 3 / 4 implementation",
        "Replace dummy data with real CM/PM logs (Day 1 of internship)",
        "Run night cycle every weekday → review morning briefs",
        "Tune prompts in Phase 5 if drift detected",
    ]
    _add_text(slide, 7.0, 1.3, 6, 0.5, "Next week",
              font_size=18, bold=True, color=COLOR_PRIMARY)
    _add_bullet(slide, 7.0, 1.8, 6, 4.0, plan, font_size=13)

    _add_text(slide, 0.6, 6.7, 12, 0.4,
              "All numbers from .tpm_context/decision_log/  ·  no LLM-fabricated metrics",
              font_size=10, color=COLOR_DIM)


# ============================================================
# Top-level
# ============================================================
def generate_slides(
    week: WeekData,
    output_dir: Path | None = None,
) -> Path:
    """Render WeekData to .pptx and return the saved path."""
    from pptx import Presentation
    from pptx.util import Inches

    output_dir = output_dir or DEFAULT_OUTPUT_DIR
    output_dir.mkdir(parents=True, exist_ok=True)

    prs = Presentation()
    prs.slide_width = Inches(13.33)   # 16:9
    prs.slide_height = Inches(7.5)

    _slide_title(prs, week)
    _slide_at_a_glance(prs, week)
    _slide_activity(prs, week)
    _slide_top_tasks(prs, week)
    _slide_quality(prs, week)
    _slide_artifacts(prs, week)
    _slide_lessons(prs, week)

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    out_path = output_dir / f"weekly_progress_{week.week_end}_{timestamp}.pptx"
    prs.save(out_path)
    log.info("progress slides written: %s", out_path)
    return out_path
